//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyatDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommissionPayment()
        {
            this.CommissionPaymentDetails = new HashSet<CommissionPaymentDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public decimal Amount { get; set; }
        public string BankPaymentNo { get; set; }
        public Nullable<System.DateTime> BankPaymentDate { get; set; }
        public int Status { get; set; }
        public bool IsVoid { get; set; }
        public int PreparingUser { get; set; }
        public int PreparingDevice { get; set; }
        public Nullable<int> ApprovingUser { get; set; }
        public Nullable<int> ApprovingDevice { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionPaymentDetail> CommissionPaymentDetails { get; set; }
    }
}
