//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyatDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionPaymentDetail
    {
        public int ID { get; set; }
        public int CommissionPaymentID { get; set; }
        public int SalesID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int CommissionID { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public int RoleID { get; set; }
    
        public virtual Commission Commission { get; set; }
        public virtual CommissionPayment CommissionPayment { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Role Role { get; set; }
    }
}
