//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyatDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commission()
        {
            this.CommissionPaymentDetails = new HashSet<CommissionPaymentDetail>();
        }
    
        public int ID { get; set; }
        public int salesID { get; set; }
        public int payID { get; set; }
        public Nullable<int> empID { get; set; }
        public int role { get; set; }
        public decimal rate { get; set; }
        public decimal amount { get; set; }
        public int status { get; set; }
        public string remark { get; set; }
    
        public virtual PaymentPlan PaymentPlan { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual Sale Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionPaymentDetail> CommissionPaymentDetails { get; set; }
    }
}
