//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyatDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee1 = new HashSet<Employee>();
            this.UserNames = new HashSet<UserName>();
        }
    
        public int ID { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string fullName { get; set; }
        public string gender { get; set; }
        public Nullable<int> role { get; set; }
        public bool isActive { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string city { get; set; }
        public string homephone { get; set; }
        public string mobilephone { get; set; }
        public string email { get; set; }
        public Nullable<int> supervisor { get; set; }
        public string remark { get; set; }
        public byte[] picture { get; set; }
        public byte[] employeeImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserName> UserNames { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
