//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyatDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Payments = new HashSet<Payment>();
            this.PaymentPlans = new HashSet<PaymentPlan>();
            this.Commissions = new HashSet<Commission>();
            this.CommissionPaymentDetails = new HashSet<CommissionPaymentDetail>();
        }
    
        public int ID { get; set; }
        public string code { get; set; }
        public int Type { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total { get; set; }
        public decimal VAT { get; set; }
        public Nullable<decimal> Ad { get; set; }
        public Nullable<decimal> FirstPayment { get; set; }
        public Nullable<decimal> RegFee { get; set; }
        public string FAName { get; set; }
        public string SAName { get; set; }
        public string EthCity { get; set; }
        public string EthSubCity { get; set; }
        public string EthWoreda { get; set; }
        public string EthHouseNo { get; set; }
        public string EthHomePhone { get; set; }
        public string EthMobileNo { get; set; }
        public string EthEmail { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string POBox { get; set; }
        public string StreetCode { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Site { get; set; }
        public string BuildingNo { get; set; }
        public int FloorNo { get; set; }
        public string HouseNo { get; set; }
        public int HouseType { get; set; }
        public decimal Area { get; set; }
        public int BedRoom { get; set; }
        public bool isActive { get; set; }
        public int PrepareuserID { get; set; }
        public int PreparedeviceID { get; set; }
        public string remark { get; set; }
        public int status { get; set; }
        public Nullable<int> ApproveuserID { get; set; }
        public Nullable<int> ApprovedeviceID { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentPlan> PaymentPlans { get; set; }
        public virtual UserName UserName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commission> Commissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionPaymentDetail> CommissionPaymentDetails { get; set; }
    }
}
